server:
  port: 8080

spring:
  flyway:
    locations: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres.postgresql.svc.cluster.local:5432/random_walk_postgres
    username: ${TWITTER_DB_USERNAME}
    password: ${TWITTER_DB_PASSWORD}
    hikari:
      schema: twitter
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
