spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URL:http://localhost:8081}
  application:
    name: twitter-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "twitter-service"

firebase:
  credentials: |
    ${FIREBASE_CREDENTIALS}